export const footerLinks = [
  { text: 'FAQ', url: 'https://help.netflix.com/support/412' },
  { text: 'Help Centre', url: 'https://help.netflix.com' },
  { text: 'Account', url: '/youraccount' },
  { text: 'Media Centre', url: 'https://media.netflix.com/' },
  { text: 'Investor Relations', url: 'http://ir.netflix.com/' },
  { text: 'Jobs', url: 'https://jobs.netflix.com/jobs' },
  { text: 'Ways to Watch', url: '/watch' },
  { text: 'Terms of Use', url: 'https://help.netflix.com/legal/termsofuse' },
  { text: 'Privacy', url: 'https://help.netflix.com/legal/privacy' },
  { text: 'Cookie Preferences', url: '#' },
  { text: 'Corporate Information', url: 'https://help.netflix.com/legal/corpinfo' },
  { text: 'Contact Us', url: 'https://help.netflix.com/contactus' },
  { text: 'Speed Test', url: 'https://fast.com' },
  { text: 'Legal Notices', url: 'https://help.netflix.com/legal/notices' },
  { text: 'Only on Netflix', url: 'https://www.netflix.com/in/browse/genre/839338' },
];
